from django.db.models import Q
from django.db import connection
from django.contrib.postgres.search import SearchQuery

import re

search_filter = {
    "aa":Q(gc__abkhazia__gt=0),
    "ab":Q(gc__afghanistan__gt=0),
    "ac":Q(gc__albania__gt=0),
    "ad":Q(gc__algeria__gt=0),
    "ae":Q(gc__andorra__gt=0),
    "af":Q(gc__angola__gt=0),
    "ag":Q(gc__antiguaandbarbuda__gt=0),
    "ah":Q(gc__argentina__gt=0),
    "ai":Q(gc__armenia__gt=0),
    "aj":Q(gc__artsakh__gt=0),
    "ak":Q(gc__australia__gt=0),
    "al":Q(gc__austria__gt=0),
    "am":Q(gc__azerbaijan__gt=0),
    "an":Q(gc__bahamas__gt=0),
    "ao":Q(gc__bahrain__gt=0),
    "ap":Q(gc__bangladesh__gt=0),
    "aq":Q(gc__barbados__gt=0),
    "ar":Q(gc__belarus__gt=0),
    "as":Q(gc__belgium__gt=0),
    "at":Q(gc__belize__gt=0),
    "au":Q(gc__benin__gt=0),
    "av":Q(gc__bhutan__gt=0),
    "aw":Q(gc__bolivia__gt=0),
    "ax":Q(gc__bosniaandherzegovina__gt=0),
    "ay":Q(gc__botswana__gt=0),
    "az":Q(gc__brazil__gt=0),
    "a0":Q(gc__bruneidarussalam__gt=0),
    "a1":Q(gc__bulgaria__gt=0),
    "a2":Q(gc__burkinafaso__gt=0),
    "a3":Q(gc__burundi__gt=0),
    "a4":Q(gc__cambodia__gt=0),
    "a5":Q(gc__cameroon__gt=0),
    "a6":Q(gc__canada__gt=0),
    "a7":Q(gc__capeverde__gt=0),
    "a8":Q(gc__catalanrepublic__gt=0),
    "a9":Q(gc__centralafricanrepublic__gt=0),
    "ba":Q(gc__chad__gt=0),
    "bb":Q(gc__chile__gt=0),
    "bc":Q(gc__china__gt=0),
    "bd":Q(gc__colombia__gt=0),
    "be":Q(gc__comoros__gt=0),
    "bf":Q(gc__congo1democratic__gt=0),
    "bg":Q(gc__congo2republic__gt=0),
    "bh":Q(gc__congo3z__gt=0),
    "bi":Q(gc__costarica__gt=0),
    "bj":Q(gc__cotedivoire__gt=0),
    "bk":Q(gc__croatia__gt=0),
    "bl":Q(gc__cuba__gt=0),
    "bm":Q(gc__cyprus__gt=0),
    "bn":Q(gc__czechrepublic__gt=0),
    "bo":Q(gc__denmark__gt=0),
    "bp":Q(gc__djibouti__gt=0),
    "bq":Q(gc__dominica2dominica__gt=0),
    "br":Q(gc__dominica1nrepublic__gt=0),
    "bs":Q(gc__easttimor__gt=0),
    "bt":Q(gc__ecuador__gt=0),
    "bu":Q(gc__egypt__gt=0),
    "bv":Q(gc__elsalvador__gt=0),
    "bw":Q(gc__eritrea__gt=0),
    "bx":Q(gc__estonia__gt=0),
    "by":Q(gc__eswatini__gt=0),
    "bz":Q(gc__ethiopia__gt=0),
    "b0":Q(gc__fiji__gt=0),
    "b1":Q(gc__finland__gt=0),
    "b2":Q(gc__france__gt=0),
    "b3":Q(gc__gabon__gt=0),
    "b4":Q(gc__gambia__gt=0),
    "b5":Q(gc__georgia__gt=0),
    "b6":Q(gc__germany__gt=0),
    "b7":Q(gc__ghana__gt=0),
    "b8":Q(gc__greece__gt=0),
    "b9":Q(gc__grenada__gt=0),
    "ca":Q(gc__guatemala__gt=0),
    "cb":Q(gc__guinea1bissau__gt=0),
    "cc":Q(gc__guinea2equatorial__gt=0),
    "cd":Q(gc__guinea3__gt=0),
    "ce":Q(gc__guyana__gt=0),
    "cf":Q(gc__haiti__gt=0),
    "cg":Q(gc__honduras__gt=0),
    "ch":Q(gc__hungary__gt=0),
    "ci":Q(gc__iceland__gt=0),
    "cj":Q(gc__india__gt=0),
    "ck":Q(gc__indonesia__gt=0),
    "cl":Q(gc__iran__gt=0),
    "cm":Q(gc__iraq__gt=0),
    "cn":Q(gc__ireland__gt=0),
    "co":Q(gc__israel__gt=0),
    "cp":Q(gc__italy__gt=0),
    "cq":Q(gc__jamaica__gt=0),
    "cr":Q(gc__japan__gt=0),
    "cs":Q(gc__jordan__gt=0),
    "ct":Q(gc__kazakhstan__gt=0),
    "cu":Q(gc__kenya__gt=0),
    "cv":Q(gc__kiribati__gt=0),
    "cw":Q(gc__korea1north__gt=0),
    "cx":Q(gc__korean2republic__gt=0),
    "cy":Q(gc__korea3z__gt=0),
    "cz":Q(gc__kosovo__gt=0),
    "c0":Q(gc__kurdistan__gt=0),
    "c1":Q(gc__kuwait__gt=0),
    "c2":Q(gc__kyrgyzstan__gt=0),
    "c3":Q(gc__laos__gt=0),
    "c4":Q(gc__latvia__gt=0),
    "c5":Q(gc__lebanon__gt=0),
    "c6":Q(gc__lesotho__gt=0),
    "c7":Q(gc__liberia__gt=0),
    "c8":Q(gc__libya__gt=0),
    "c9":Q(gc__liechtenstein__gt=0),
    "da":Q(gc__lithuania__gt=0),
    "db":Q(gc__luxembourg__gt=0),
    "dc":Q(gc__madagascar__gt=0),
    "dd":Q(gc__malawi__gt=0),
    "de":Q(gc__malaysia__gt=0),
    "df":Q(gc__maldives__gt=0),
    "dg":Q(gc__mali__gt=0),
    "dh":Q(gc__malta__gt=0),
    "di":Q(gc__marshallislands__gt=0),
    "dj":Q(gc__mauritania__gt=0),
    "dk":Q(gc__mauritius__gt=0),
    "dl":Q(gc__mexico__gt=0),
    "dm":Q(gc__micronesia__gt=0),
    "dn":Q(gc__moldovan1republicpridnestrovian__gt=0),
    "do":Q(gc__moldova2__gt=0),
    "dp":Q(gc__monaco__gt=0),
    "dq":Q(gc__mongolia__gt=0),
    "dr":Q(gc__montenegro__gt=0),
    "ds":Q(gc__morocco__gt=0),
    "dt":Q(gc__mozambique__gt=0),
    "du":Q(gc__myanmar__gt=0),
    "dv":Q(gc__namibia__gt=0),
    "dw":Q(gc__nauru__gt=0),
    "dx":Q(gc__nepal__gt=0),
    "dy":Q(gc__netherlands__gt=0),
    "dz":Q(gc__newzealand__gt=0),
    "d0":Q(gc__nicaragua__gt=0),
    "d1":Q(gc__niger__gt=0),
    "d2":Q(gc__nigeria__gt=0),
    "d3":Q(gc__northcyprus__gt=0),
    "d4":Q(gc__northmacedonia__gt=0),
    "d5":Q(gc__norway__gt=0),
    "d6":Q(gc__oman__gt=0),
    "d7":Q(gc__pakistan__gt=0),
    "d8":Q(gc__palau__gt=0),
    "d9":Q(gc__palestine__gt=0),
    "ea":Q(gc__panama__gt=0),
    "eb":Q(gc__papuanewguinea__gt=0),
    "ec":Q(gc__paraguay__gt=0),
    "ed":Q(gc__peru__gt=0),
    "ee":Q(gc__philippines__gt=0),
    "ef":Q(gc__poland__gt=0),
    "eg":Q(gc__portugal__gt=0),
    "eh":Q(gc__puntland__gt=0),
    "ei":Q(gc__qatar__gt=0),
    "ej":Q(gc__romania__gt=0),
    "ek":Q(gc__russia__gt=0),
    "el":Q(gc__rwanda__gt=0),
    "em":Q(gc__sahrawiarabdemocraticrepublic__gt=0),
    "en":Q(gc__saintkittsandnevis__gt=0),
    "eo":Q(gc__saintlucia__gt=0),
    "ep":Q(gc__saintvincentandthegrenadines__gt=0),
    "eq":Q(gc__samoa__gt=0),
    "er":Q(gc__sanmarino__gt=0),
    "es":Q(gc__saotomeandprincipe__gt=0),
    "et":Q(gc__saudiarabia__gt=0),
    "eu":Q(gc__senegal__gt=0),
    "ev":Q(gc__serbia__gt=0),
    "ew":Q(gc__seychelles__gt=0),
    "ex":Q(gc__sierraleone__gt=0),
    "ey":Q(gc__singapore__gt=0),
    "ez":Q(gc__slovakia__gt=0),
    "e0":Q(gc__slovenia__gt=0),
    "e1":Q(gc__solomonislands__gt=0),
    "e2":Q(gc__somalia__gt=0),
    "e3":Q(gc__somaliland__gt=0),
    "e4":Q(gc__southafrica__gt=0),
    "e5":Q(gc__southkorea__gt=0),
    "e6":Q(gc__southossetia__gt=0),
    "e7":Q(gc__southsudan__gt=0),
    "e8":Q(gc__spain__gt=0),
    "e9":Q(gc__srilanka__gt=0),
    "fa":Q(gc__sudan__gt=0),
    "fb":Q(gc__suriname__gt=0),
    "fc":Q(gc__sweden__gt=0),
    "fd":Q(gc__switzerland__gt=0),
    "fe":Q(gc__syria__gt=0),
    "ff":Q(gc__tajikistan__gt=0),
    "fg":Q(gc__tanzania__gt=0),
    "fh":Q(gc__thailand__gt=0),
    "fi":Q(gc__tibet__gt=0),
    "fj":Q(gc__togo__gt=0),
    "fk":Q(gc__tonga__gt=0),
    "fl":Q(gc__trinidadandtobago__gt=0),
    "fm":Q(gc__tunisia__gt=0),
    "fn":Q(gc__turkey__gt=0),
    "fo":Q(gc__turkmenistan__gt=0),
    "fp":Q(gc__tuvalu__gt=0),
    "fq":Q(gc__uganda__gt=0),
    "fr":Q(gc__ukraine__gt=0),
    "fs":Q(gc__unitedarabemirates__gt=0),
    "ft":Q(gc__unitedkingdom__gt=0),
    "fu":Q(gc__unitedstates__gt=0),
    "fv":Q(gc__uruguay__gt=0),
    "fw":Q(gc__uzbekistan__gt=0),
    "fx":Q(gc__vanuatu__gt=0),
    "fy":Q(gc__vaticancity__gt=0),
    "fz":Q(gc__venezuela__gt=0),
    "f0":(Q(gc__vietnam2__gt=0) | Q(gc__vietnam1__gt=0)),
    "f1":Q(gc__yemen__gt=0),
    "f2":Q(gc__zambia__gt=0),
    "f3":Q(gc__zimbabwe__gt=0),
    "f4":Q(gr__africa__gt=0),
    "f5":Q(gr__arab_world__gt=0),
    "f6":Q(gr__asia_pacific__gt=0),
    "f7":Q(gr__caribbean__gt=0),
    "f8":Q(gr__central_africa__gt=0),
    "f9":Q(gr__central_america__gt=0),
    "ga":Q(gr__central_asia__gt=0),
    "gb":Q(gr__east_africa__gt=0),
    "gc":Q(gr__east_africa_community__gt=0),
    "gd":Q(gr__east_asia__gt=0),
    "ge":Q(gr__east_asia_and_pacific__gt=0),
    "gf":Q(gr__eastern_africa__gt=0),
    "gg":Q(gr__eastern_asia__gt=0),
    "gh":Q(gr__europe_and_central_asia__gt=0),
    "gi":Q(gr__horn_of_africa__gt=0),
    "gj":Q(gr__latin_america__gt=0),
    "gk":Q(gr__latin_america_and_caribbean__gt=0),
    "gl":Q(gr__middle_africa__gt=0),
    "gm":Q(gr__middle_east__gt=0),
    "gn":Q(gr__middle_east_and_north_africa__gt=0),
    "go":Q(gr__north_africa__gt=0),
    "gp":Q(gr__northern_africa__gt=0),
    "gq":Q(gr__pacific__gt=0),
    "gr":Q(gr__polynesia__gt=0),
    "gs":Q(gr__small_island_development_states__gt=0),
    "gt":Q(gr__southern_african_development_community__gt=0),
    "gu":Q(gr__south_america__gt=0),
    "gv":Q(gr__south_asia__gt=0),
    "gw":Q(gr__south_asia_region__gt=0),
    "gx":Q(gr__southeast_asia__gt=0),
    "gy":Q(gr__southeastern_asia__gt=0),
    "gz":Q(gr__southern_africa__gt=0),
    "g0":Q(gr__southern_asia__gt=0),
    "g1":Q(gr__sub_saharan_africa__gt=0),
    "g2":Q(gr__west_africa__gt=0),
    "g3":Q(gr__western_africa__gt=0),
    "g4":Q(gr__western_asia__gt=0),
    "g5":Q(gd__conflict_affected_areas__gt=0),
    "g6":Q(gd__conflict_affected_regions__gt=0),
    "g7":Q(gd__developing_context__gt=0),
    "g8":Q(gd__developing_countries__gt=0),
    "g9":Q(gd__developing_country__gt=0),
    "ha":Q(gd__developing_economy__gt=0),
    "hb":Q(gd__developing_market_countries__gt=0),
    "hc":Q(gd__developing_markets__gt=0),
    "hd":Q(gd__developing_nation__gt=0),
    "he":Q(gd__developing_region__gt=0),
    "hf":Q(gd__developing_state__gt=0),
    "hg":Q(gd__developing_world__gt=0),
    "hh":Q(gd__emergent_nation__gt=0),
    "hi":Q(gd__emerging_economies__gt=0),
    "hj":Q(gd__emerging_market_countries__gt=0),
    "hk":Q(gd__emerging_nation__gt=0),
    "hl":Q(gd__emerging_world__gt=0),
    "hm":Q(gd__fragile_and_conflict_affected_areas__gt=0),
    "hn":Q(gd__fragile_and_conflict_affected_regions__gt=0),
    "ho":Q(gd__fragile_areas__gt=0),
    "hp":Q(gd__fragile_contexts__gt=0),
    "hq":Q(gd__fragile_regions__gt=0),
    "hr":Q(gd__global_south__gt=0),
    "hs":Q(gd__growing_economies__gt=0),
    "ht":Q(gd__less_developed_countries__gt=0),
    "hu":Q(gd__lmic__gt=0),
    "hv":Q(gd__low_income_countries1__gt=0),
    "hw":Q(gd__low_income_environment1__gt=0),
    "hx":Q(gd__low_resource_countries1__gt=0),
    "hy":Q(gd__low_resource_environment1__gt=0),
    "hz":Q(gd__low_income_countries2__gt=0),
    "h0":Q(gd__low_income_environment2__gt=0),
    "h1":Q(gd__low_resource_countries2__gt=0),
    "h2":Q(gd__low_resource_environment2__gt=0),
    "h3":Q(gd__middle_income_country__gt=0),
    "h4":Q(gd__middle_income_environment__gt=0),
    "h5":Q(gd__third_world__gt=0),
    "h6":Q(gd__under_developed_countries__gt=0),
    "h7":Q(gd__under_developed_nation__gt=0),
    "h8":Q(p1__classroom_assistants__gt=0),
    "h9":Q(p1__classroom_instruction__gt=0),
    "ia":Q(p1__district_education_officer__gt=0),
    "ib":Q(p1__early_childhood_development__gt=0),
    "ic":Q(p1__early_childhood_education__gt=0),
    "id":Q(p1__educators__gt=0),
    "ie":Q(p1__elementary_education__gt=0),
    "if":Q(p1__elementary_school__gt=0),
    "ig":Q(p1__faith_school__gt=0),
    "ih":Q(p1__headteacher__gt=0),
    "ii":Q(p1__high_school__gt=0),
    "ij":Q(p1__junior_middle_school__gt=0),
    "ik":Q(p1__junior_school__gt=0),
    "il":Q(p1__k_12__gt=0),
    "im":Q(p1__kindergarten__gt=0),
    "in":Q(p1__school_director__gt=0),
    "io":Q(p1__middle_school1__gt=0),
    "ip":Q(p1__middle_school2__gt=0),
    "iq":Q(p1__ministry_of_education__gt=0),
    "ir":Q(p1__nursery__gt=0),
    "is":Q(p1__post_primary1__gt=0),
    "it":Q(p1__post_primary2__gt=0),
    "iu":Q(p1__pre_primary1__gt=0),
    "iv":Q(p1__pre_primary2__gt=0),
    "iw":Q(p1__pre_school__gt=0),
    "ix":Q(p1__pre_service_teachers__gt=0),
    "iy":Q(p1__primary_education__gt=0),
    "iz":Q(p1__primary_school__gt=0),
    "i0":Q(p1__principal__gt=0),
    "i1":Q(p1__private_school__gt=0),
    "i2":Q(p1__refugee_educator__gt=0),
    "i3":Q(p1__school__gt=0),
    "i4":Q(p1__school_administrator__gt=0),
    "i5":Q(p1__school_authority__gt=0),
    "i6":Q(p1__school_governing_body__gt=0),
    "i7":Q(p1__school_head__gt=0),
    "i8":Q(p1__school_leadership_team__gt=0),
    "i9":Q(p1__school_management_team__gt=0),
    "ja":Q(p1__school_offical__gt=0),
    "jb":Q(p1__school_principal__gt=0),
    "jc":Q(p1__school_supervisor__gt=0),
    "jd":Q(p1__school_teacher__gt=0),
    "je":Q(p1__secondary_education__gt=0),
    "jf":Q(p1__secondary_school__gt=0),
    "jg":Q(p1__senior_leadership_team__gt=0),
    "jh":Q(p1__state_school__gt=0),
    "ji":Q(p1__teacher_candidates__gt=0),
    "jj":Q(p1__teacher_certificate__gt=0),
    "jk":Q(p1__teacher_cop__gt=0),
    "jl":Q(p1__teacher_education__gt=0),
    "jm":Q(p1__teacher_professional_development__gt=0),
    "jn":Q(p1__teacher_training__gt=0),
    "jo":Q(p1__teacher_training_centre__gt=0),
    "jp":Q(p1__teacher_training_college__gt=0),
    "jq":Q(p1__teacher_training_institute__gt=0),
    "jr":Q(p1__teachers__gt=0),
    "js":Q(p1__teaching_assistant__gt=0),
    "jt":Q(p1__teaching_assistants__gt=0),
    "ju":Q(p1__teaching_certificate__gt=0),
    "jv":Q(p2__accessible_learning__gt=0),
    "jw":Q(p2__alien__gt=0),
    "jx":Q(p2__alienation__gt=0),
    "jy":Q(p2__asylum__gt=0),
    "jz":Q(p2__asylum_seeker__gt=0),
    "j0":Q(p2__at_risk_population__gt=0),
    "j1":Q(p2__bachelors_degree1__gt=0),
    "j2":Q(p2__bachelors_degree2__gt=0),
    "j3":Q(p2__career_entry_support1__gt=0),
    "j4":Q(p2__career_entry_support2__gt=0),
    "j5":Q(p2__career_path_training__gt=0),
    "j6":Q(p2__church__gt=0),
    "j7":Q(p2__community_education__gt=0),
    "j8":Q(p2__competency_based_training__gt=0),
    "j9":Q(p2__continuing_education__gt=0),
    "ka":Q(p2__continuing_training__gt=0),
    "kb":Q(p2__continuous_professional_development__gt=0),
    "kc":Q(p2__degree__gt=0),
    "kd":Q(p2__diploma__gt=0),
    "ke":Q(p2__disabilities__gt=0),
    "kf":Q(p2__disability__gt=0),
    "kg":Q(p2__district_level__gt=0),
    "kh":Q(p2__displaced_person__gt=0),
    "ki":Q(p2__displaced_populations__gt=0),
    "kj":Q(p2__education__gt=0),
    "kk":Q(p2__education_in_emergencies__gt=0),
    "kl":Q(p2__favela__gt=0),
    "km":Q(p2__fragility_in_education__gt=0),
    "kn":Q(p2__gang_members__gt=0),
    "ko":Q(p2__geographically_dispersed__gt=0),
    "kp":Q(p2__in_service_training__gt=0),
    "kq":Q(p2__informal_education__gt=0),
    "kr":Q(p2__informal_learning__gt=0),
    "ks":Q(p2__informal_training__gt=0),
    "kt":Q(p2__language_learning__gt=0),
    "ku":Q(p2__learning_community__gt=0),
    "kv":Q(p2__masters_degree__gt=0),
    "kw":Q(p2__masters__gt=0),
    "kx":Q(p2__math__gt=0),
    "ky":Q(p2__mathematics__gt=0),
    "kz":Q(p2__migrant__gt=0),
    "k0":Q(p2__minority_ethnic_group__gt=0),
    "k1":Q(p2__mosque__gt=0),
    "k2":Q(p2__moving_populations__gt=0),
    "k3":Q(p2__natural_science__gt=0),
    "k4":Q(p2__non_formal_education__gt=0),
    "k5":Q(p2__non_formal_learning__gt=0),
    "k6":Q(p2__postsecondary_education__gt=0),
    "k7":Q(p2__pre_service_training__gt=0),
    "k8":Q(p2__professional_continuing_education__gt=0),
    "k9":Q(p2__professional_education__gt=0),
    "la":Q(p2__professional_learning_community__gt=0),
    "lb":Q(p2__professional_qualification__gt=0),
    "lc":Q(p2__professional_re_education__gt=0),
    "ld":Q(p2__professional_studies__gt=0),
    "le":Q(p2__professional_training__gt=0),
    "lf":Q(p2__qualification__gt=0),
    "lg":Q(p2__refugee_education__gt=0),
    "lh":Q(p2__refugee_learning__gt=0),
    "li":Q(p2__science__gt=0),
    "lj":Q(p2__science_and_technology__gt=0),
    "lk":Q(p2__science_technology_engineering_and_applied_mathematics__gt=0),
    "ll":Q(p2__science_technology_engineering_and_mathematics__gt=0),
    "lm":Q(p2__slum__gt=0),
    "ln":Q(p2__special_educational_needs__gt=0),
    "lo":Q(p2__sen_learner__gt=0),
    "lp":Q(p2__sen_student__gt=0),
    "lq":Q(p2__special_educational_needs_and_disabilities__gt=0),
    "lr":Q(p2__special_needs_students__gt=0),
    "ls":Q(p2__street_children__gt=0),
    "lt":Q(p2__students__gt=0),
    "lu":Q(p2__students_with_disabilities__gt=0),
    "lv":Q(p2__technical_training__gt=0),
    "lw":Q(p2__technical_and_vocational_education_and_training__gt=0),
    "lx":Q(p2__vocational_training__gt=0),
    "ly":Q(p2__young_people__gt=0),
    "lz":Q(p2__youth__gt=0),
    "l0":Q(r__action_research__gt=0),
    "l1":Q(r__adaptive__gt=0),
    "l2":Q(r__agile__gt=0),
    "l3":Q(r__anarchy__gt=0),
    "l4":Q(r__case_study__gt=0),
    "l5":Q(r__citizen_science__gt=0),
    "l6":Q(r__correlation__gt=0),
    "l7":Q(r__critical_realism__gt=0),
    "l8":Q(r__critical_theory__gt=0),
    "l9":Q(r__design_based_implementation_research__gt=0),
    "ma":Q(r__design_based_research__gt=0),
    "mb":Q(r__deductive__gt=0),
    "mc":Q(r__difference_in_differences__gt=0),
    "md":Q(r__engineering_based_research__gt=0),
    "me":Q(r__evaluation__gt=0),
    "mf":Q(r__experimental_design__gt=0),
    "mg":Q(r__focus_groups__gt=0),
    "mh":Q(r__formative_research__gt=0),
    "mi":Q(r__grounded_theory__gt=0),
    "mj":Q(r__group_discussions__gt=0),
    "mk":Q(r__hermeneutics__gt=0),
    "ml":Q(r__historical__gt=0),
    "mm":Q(r__impact__gt=0),
    "mn":Q(r__inductive__gt=0),
    "mo":Q(r__interview__gt=0),
    "mp":Q(r__iterative__gt=0),
    "mq":Q(r__lean__gt=0),
    "mr":Q(r__learning_analytics__gt=0),
    "ms":Q(r__literature_analysis__gt=0),
    "mt":Q(r__literature_review__gt=0),
    "mu":Q(r__long_interview__gt=0),
    "mv":Q(r__meta_analysis__gt=0),
    "mw":Q(r__mixed_method__gt=0),
    "mx":Q(r__modelling__gt=0),
    "my":Q(r__observation__gt=0),
    "mz":Q(r__participatory_video__gt=0),
    "m0":Q(r__positivist__gt=0),
    "m1":Q(r__quasi_experimental_design__gt=0),
    "m2":Q(r__qualitative__gt=0),
    "m3":Q(r__quantitative__gt=0),
    "m4":Q(r__questionnaire__gt=0),
    "m5":Q(r__randomised_control_trial__gt=0),
    "m6":Q(r__regression__gt=0),
    "m7":Q(r__regression_discontinuity_design__gt=0),
    "m8":Q(r__research_design__gt=0),
    "m9":Q(r__research_method__gt=0),
    "na":Q(r__rich_text_analysis__gt=0),
    "nb":Q(r__semi_structured_interview__gt=0),
    "nc":Q(r__structured_interview__gt=0),
    "nd":Q(r__survey__gt=0),
    "ne":Q(r__synthesis__gt=0),
    "nf":Q(r__systematic_review__gt=0),
    "ng":Q(r__tracer_study__gt=0),
    "nh":Q(r__trial__gt=0),
    "ni":Q(r__unstructured_interview__gt=0),
    "nj":Q(r__usability__gt=0),
    "nk":Q(r__video__gt=0),
    "nl":Q(r__program_evaluation__gt=0),
    "nm":Q(r__programme_evaluation__gt=0),
    "nn":Q(te__electronic_whiteboard__gt=0),
    "no":Q(te__interactive_whiteboard__gt=0),
    "np":Q(te__smart_board__gt=0),
    "nq":Q(te__smartboard__gt=0),
    "nr":Q(te__electronic_textbook__gt=0),
    "ns":Q(te__etutor__gt=0),
    "nt":Q(te__free_digital_resources__gt=0),
    "nu":Q(te__intelligent_agent__gt=0),
    "nv":Q(te__intelligent_tutoring_system__gt=0),
    "nw":Q(te__learning_platform__gt=0),
    "nx":Q(te__massive_open_online_course__gt=0),
    "ny":Q(te__moodle__gt=0),
    "nz":Q(te__open_educational_resources__gt=0),
    "n0":Q(te__online_textbook__gt=0),
    "n1":Q(te__online_tutor__gt=0),
    "n2":Q(te__reusable_learning_object__gt=0),
    "n3":Q(te__school_website__gt=0),
    "n4":Q(te__edtech__gt=0),
    "n5":Q(te__educational_innovation__gt=0),
    "n6":Q(te__educational_technologies__gt=0),
    "n7":Q(te__emerging_education_technologies__gt=0),
    "n8":Q(te__emerging_education_technology__gt=0),
    "n9":Q(te__ict_in_classrooms__gt=0),
    "oa":Q(te__ict_in_the_classroom__gt=0),
    "ob":Q(te__technology_at_school__gt=0),
    "oc":Q(te__technology_in_education__gt=0),
    "od":Q(te__technology_in_school__gt=0),
    "oe":Q(te__technology_use_in_education__gt=0),
    "of":Q(te__adaptive_learning__gt=0),
    "og":Q(te__asynchronous_learning__gt=0),
    "oh":Q(te__blended_learning__gt=0),
    "oi":Q(te__computer_assisted_instruction1__gt=0),
    "oj":Q(te__computer_assisted_instruction2__gt=0),
    "ok":Q(te__computer_assisted_learning__gt=0),
    "ol":Q(te__computer_based_assessment__gt=0),
    "om":Q(te__computer_based_instruction__gt=0),
    "on":Q(te__computer_managed_instruction__gt=0),
    "oo":Q(te__computer_mediated_learning__gt=0),
    "op":Q(te__computer_supported_collaborative_learning__gt=0),
    "oq":Q(te__computer_supported_education__gt=0),
    "or":Q(te__computer_assisted_instructional_programme__gt=0),
    "os":Q(te__computerised_learning__gt=0),
    "ot":Q(te__connected_learning__gt=0),
    "ou":Q(te__differentiated_learning__gt=0),
    "ov":Q(te__digital_learning__gt=0),
    "ow":Q(te__distance_education__gt=0),
    "ox":Q(te__distance_learning__gt=0),
    "oy":Q(te__distance_learning_program__gt=0),
    "oz":Q(te__distributed_learning__gt=0),
    "o0":Q(te__e_learning__gt=0),
    "o1":Q(te__electronic_classroom__gt=0),
    "o2":Q(te__flipped_classroom__gt=0),
    "o3":Q(te__flipped_learning__gt=0),
    "o4":Q(te__free_digital_learning__gt=0),
    "o5":Q(te__gamification__gt=0),
    "o6":Q(te__hybrid_learning__gt=0),
    "o7":Q(te__individualised_learning__gt=0),
    "o8":Q(te__instructional_innovation__gt=0),
    "o9":Q(te__instructional_technology__gt=0),
    "pa":Q(te__integrated_learning_systems__gt=0),
    "pb":Q(te__interactive_learning_environment__gt=0),
    "pc":Q(te__learning__gt=0),
    "pd":Q(te__media_literacy__gt=0),
    "pe":Q(te__microlearning__gt=0),
    "pf":Q(te__mobile_education__gt=0),
    "pg":Q(te__mobile_learning__gt=0),
    "ph":Q(te__multimedia_instruction__gt=0),
    "pi":Q(te__open_and_distance_elearning__gt=0),
    "pj":Q(te__open_and_distance_learning__gt=0),
    "pk":Q(te__online_course__gt=0),
    "pl":Q(te__online_lab__gt=0),
    "pm":Q(te__online_laboratory__gt=0),
    "pn":Q(te__online_learning__gt=0),
    "po":Q(te__open_education__gt=0),
    "pp":Q(te__open_learning__gt=0),
    "pq":Q(te__personalised_learning__gt=0),
    "pr":Q(te__personalised_teaching__gt=0),
    "ps":Q(te__plasma_based_instruction__gt=0),
    "pt":Q(te__self_directed_learning__gt=0),
    "pu":Q(te__self_paced_learning__gt=0),
    "pv":Q(te__synchronous_online_learning__gt=0),
    "pw":Q(te__technological_pedagogical_content__gt=0),
    "px":Q(te__technology_assisted_learning1__gt=0),
    "py":Q(te__technology_engagement_teaching_strategy__gt=0),
    "pz":Q(te__technology_enhanced_learning__gt=0),
    "p0":Q(te__technology_integration__gt=0),
    "p1":Q(te__technology_assisted_learning2__gt=0),
    "p2":Q(te__tele_education__gt=0),
    "p3":Q(te__virtual_classroom__gt=0),
    "p4":Q(te__virtual_learning__gt=0),
    "p5":Q(te__virtual_learning_environment__gt=0),
    "p6":Q(te__virtual_school__gt=0),
    "p7":Q(te__web_based_instruction__gt=0),
    "p8":Q(te__webinar__gt=0),
    "p9":Q(te__course_management_system__gt=0),
    "qa":Q(te__education_management_information_system__gt=0),
    "qb":Q(te__examination_systems__gt=0),
    "qc":Q(te__learning_management_systems__gt=0),
    "qd":Q(te__teacher_development_software__gt=0),
    "qe":Q(te__textbook_analytics__gt=0),
    "qf":Q(tt__field_3d_printer__gt=0),
    "qg":Q(tt__field_3d_printing__gt=0),
    "qh":Q(tt__access_to_computers__gt=0),
    "qi":Q(tt__accessible_technologies__gt=0),
    "qj":Q(tt__alternative_communication__gt=0),
    "qk":Q(tt__android__gt=0),
    "ql":Q(tt__app__gt=0),
    "qm":Q(tt__apple__gt=0),
    "qn":Q(tt__assistive_technology__gt=0),
    "qo":Q(tt__audio_recording__gt=0),
    "qp":Q(tt__augmentative_communication__gt=0),
    "qq":Q(tt__bada__gt=0),
    "qr":Q(tt__bandwidth__gt=0),
    "qs":Q(tt__barriers_to_technology__gt=0),
    "qt":Q(tt__big_data__gt=0),
    "qu":Q(tt__blackberry__gt=0),
    "qv":Q(tt__blog__gt=0),
    "qw":Q(tt__camera__gt=0),
    "qx":Q(tt__cellphone__gt=0),
    "qy":Q(tt__chatbot__gt=0),
    "qz":Q(tt__clicker_technology__gt=0),
    "q0":Q(tt__clickers__gt=0),
    "q1":Q(tt__cloud__gt=0),
    "q2":Q(tt__cmc__gt=0),
    "q3":Q(tt__computational_thinking_literacy__gt=0),
    "q4":Q(tt__computer__gt=0),
    "q5":Q(tt__computer_illiteracy__gt=0),
    "q6":Q(tt__computer_literacy__gt=0),
    "q7":Q(tt__computer_mediated_communication__gt=0),
    "q8":Q(tt__computerised__gt=0),
    "q9":Q(tt__computers_on_wheels__gt=0),
    "ra":Q(tt__connectivity__gt=0),
    "rb":Q(tt__ct_literacy__gt=0),
    "rc":Q(tt__data__gt=0),
    "rd":Q(tt__digital_communication__gt=0),
    "re":Q(tt__digital_content__gt=0),
    "rf":Q(tt__digital_divide__gt=0),
    "rg":Q(tt__digital_exclusion__gt=0),
    "rh":Q(tt__digital_immigrants__gt=0),
    "ri":Q(tt__digital_inclusion__gt=0),
    "rj":Q(tt__digital_literacy__gt=0),
    "rk":Q(tt__digital_native__gt=0),
    "rl":Q(tt__digital_resources__gt=0),
    "rm":Q(tt__digital_scrapbook__gt=0),
    "rn":Q(tt__digital_skills__gt=0),
    "ro":Q(tt__digital_storytelling__gt=0),
    "rp":Q(tt__digital_technology__gt=0),
    "rq":Q(tt__digital_transformation__gt=0),
    "rr":Q(tt__digitalised__gt=0),
    "rs":Q(tt__digitised__gt=0),
    "rt":Q(tt__discord__gt=0),
    "ru":Q(tt__disruptive_technology__gt=0),
    "rv":Q(tt__douban__gt=0),
    "rw":Q(tt__douyin__gt=0),
    "rx":Q(tt__dvd_player__gt=0),
    "ry":Q(tt__e_book__gt=0),
    "rz":Q(tt__e_reader__gt=0),
    "r0":Q(tt__earphones__gt=0),
    "r1":Q(tt__ebook__gt=0),
    "r2":Q(tt__ereader__gt=0),
    "r3":Q(tt__facebook__gt=0),
    "r4":Q(tt__gadget__gt=0),
    "r5":Q(tt__game_console__gt=0),
    "r6":Q(tt__garnet__gt=0),
    "r7":Q(tt__geographical_information_systems__gt=0),
    "r8":Q(tt__hardware__gt=0),
    "r9":Q(tt__headphones__gt=0),
    "sa":Q(tt__holograms__gt=0),
    "sb":Q(tt__i_pad__gt=0),
    "sc":Q(tt__ict__gt=0),
    "sd":Q(tt__inclusive_technologies__gt=0),
    "se":Q(tt__influence_of_technology__gt=0),
    "sf":Q(tt__information_communications_technology_literacy__gt=0),
    "sg":Q(tt__information_literacy__gt=0),
    "sh":Q(tt__instagram__gt=0),
    "si":Q(tt__instructional_systems__gt=0),
    "sj":Q(tt__integration_of_technology__gt=0),
    "sk":Q(tt__intel__gt=0),
    "sl":Q(tt__interactive__gt=0),
    "sm":Q(tt__internet__gt=0),
    "sn":Q(tt__internet_access__gt=0),
    "so":Q(tt__internet_domain__gt=0),
    "sp":Q(tt__internet_of_things__gt=0),
    "sq":Q(tt__ios__gt=0),
    "sr":Q(tt__ipad__gt=0),
    "ss":Q(tt__iphone__gt=0),
    "st":Q(tt__information_technology__gt=0),
    "su":Q(tt__keyboard__gt=0),
    "sv":Q(tt__kindle__gt=0),
    "sw":Q(tt__laptop__gt=0),
    "sx":Q(tt__linkedin__gt=0),
    "sy":Q(tt__maemo__gt=0),
    "sz":Q(tt__meego__gt=0),
    "s0":Q(tt__metadata__gt=0),
    "s1":Q(tt__microsoft__gt=0),
    "s2":Q(tt__mobile_phone__gt=0),
    "s3":Q(tt__new_media__gt=0),
    "s4":Q(tt__new_technologies__gt=0),
    "s5":Q(tt__offline__gt=0),
    "s6":Q(tt__online__gt=0),
    "s7":Q(tt__online_discussion__gt=0),
    "s8":Q(tt__open_source__gt=0),
    "s9":Q(tt__open_source_software__gt=0),
    "ta":Q(tt__open_wedos__gt=0),
    "tb":Q(tt__operating_system__gt=0),
    "tc":Q(tt__palm_os__gt=0),
    "td":Q(tt__pinterest__gt=0),
    "te":Q(tt__platform__gt=0),
    "tf":Q(tt__podcast__gt=0),
    "tg":Q(tt__poll_everywhere__gt=0),
    "th":Q(tt__printer__gt=0),
    "ti":Q(tt__qq__gt=0),
    "tj":Q(tt__qzone__gt=0),
    "tk":Q(tt__rachel__gt=0),
    "tl":Q(tt__rachel_server__gt=0),
    "tm":Q(tt__radio__gt=0),
    "tn":Q(tt__raspberry_pi__gt=0),
    "to":Q(tt__reddit__gt=0),
    "tp":Q(tt__sd_card__gt=0),
    "tq":Q(tt__simulation__gt=0),
    "tr":Q(tt__sina_weibo__gt=0),
    "ts":Q(tt__single_board_computer__gt=0),
    "tt":Q(tt__snapchat__gt=0),
    "tu":Q(tt__social_media__gt=0),
    "tv":Q(tt__social_network__gt=0),
    "tw":Q(tt__social_networking_sites__gt=0),
    "tx":Q(tt__software__gt=0),
    "ty":Q(tt__supportive_technology__gt=0),
    "tz":Q(tt__symbian__gt=0),
    "t0":Q(tt__tablet__gt=0),
    "t1":Q(tt__technological_literacy__gt=0),
    "t2":Q(tt__technology_leapfrogging__gt=0),
    "t3":Q(tt__technology_enhanced__gt=0),
    "t4":Q(tt__telephone__gt=0),
    "t5":Q(tt__television__gt=0),
    "t6":Q(tt__tiktok__gt=0),
    "t7":Q(tt__twitter__gt=0),
    "t8":Q(tt__verdict__gt=0),
    "t9":Q(tt__viber__gt=0),
    "ua":Q(tt__video_recorder__gt=0),
    "ub":Q(tt__videoconferencing__gt=0),
    "uc":Q(tt__virtual_peer__gt=0),
    "ud":Q(tt__virtual_reality__gt=0),
    "ue":Q(tt__web__gt=0),
    "uf":Q(tt__wechat__gt=0),
    "ug":Q(tt__whatsapp__gt=0),
    "uh":Q(tt__wifi__gt=0),
    "ui":Q(tt__wikipedia__gt=0),
    "uj":Q(tt__windows__gt=0),
    "uk":Q(tt__youtube__gt=0),
    "ul":Q(o__alison__gt=0),
    "um":Q(o__brck__gt=0),
    "un":Q(o__bridge__gt=0),
    "uo":Q(o__ck_12__gt=0),
    "up":Q(o__coursera__gt=0),
    "uq":Q(o__dr_maths__gt=0),
    "ur":Q(o__edx__gt=0),
    "us":Q(o__egyptian_teachers_first_professional_development_program__gt=0),
    "ut":Q(o__ekstep__gt=0),
    "uu":Q(o__emo_haiti__gt=0),
    "uv":Q(o__eneza__gt=0),
    "uw":Q(o__enlaces__gt=0),
    "ux":Q(o__enuma__gt=0),
    "uy":Q(o__foundation_for_learning_equality__gt=0),
    "uz":Q(o__futurelearn__gt=0),
    "u0":Q(o__geekie__gt=0),
    "u1":Q(o__hip2bsquared__gt=0),
    "u2":Q(o__inable__gt=0),
    "u3":Q(o__khan_academy1__gt=0),
    "u4":Q(o__khan_academy2__gt=0),
    "u5":Q(o__khanya_project__gt=0),
    "u6":Q(o__kolibri__gt=0),
    "u7":Q(o__lego_project__gt=0),
    "u8":Q(o__mindspark__gt=0),
    "u9":Q(o__mobilearn__gt=0),
    "va":Q(o__mxit__gt=0),
    "vb":Q(o__nafham__gt=0),
    "vc":Q(o__ole__gt=0),
    "vd":Q(o__one_billion__gt=0),
    "ve":Q(o__one_laptop_per_child__gt=0),
    "vf":Q(o__pratham_books_storyweaver__gt=0),
    "vg":Q(o__retel__gt=0),
    "vh":Q(o__rumie__gt=0),
    "vi":Q(o__scratch__gt=0),
    "vj":Q(o__siyavula__gt=0),
    "vk":Q(o__ted__gt=0),
    "vl":Q(o__the_connected_learning_initiative__gt=0),
    "vm":Q(o__the_egyptian_knowledge_bank__gt=0),
    "vn":Q(o__the_global_digital_library__gt=0),
    "vo":Q(o__the_queen_rania_teacher_academy__gt=0),
    "vp":Q(o__ubongo__gt=0),
    "vq":Q(o__udacity__gt=0),
    "vr":Q(o__university_of_the_people__gt=0),
    "vs":Q(o__worldreader__gt=0),
    "vt":Q(o__xuetangx__gt=0),
    "vu":Q(o__yoza__gt=0),
    "vv":Q(f__field_21st_century_learning__gt=0),
    "vw":Q(f__academic_achievement__gt=0),
    "vx":Q(f__access__gt=0),
    "vy":Q(f__access_to_education__gt=0),
    "vz":Q(f__accessibility__gt=0),
    "v0":Q(f__accountability__gt=0),
    "v1":Q(f__achievement__gt=0),
    "v2":Q(f__achievement_gap__gt=0),
    "v3":Q(f__aid__gt=0),
    "v4":Q(f__assessment__gt=0),
    "v5":Q(f__attainment__gt=0),
    "v6":Q(f__attendance__gt=0),
    "v7":Q(f__attitude__gt=0),
    "v8":Q(f__attribution__gt=0),
    "v9":Q(f__bank__gt=0),
    "wa":Q(f__banking__gt=0),
    "wb":Q(f__behavior__gt=0),
    "wc":Q(f__behaviour__gt=0),
    "wd":Q(f__budgeting__gt=0),
    "we":Q(f__change_management__gt=0),
    "wf":Q(f__charity__gt=0),
    "wg":Q(f__constraints__gt=0),
    "wh":Q(f__constructivism__gt=0),
    "wi":Q(f__constructivist__gt=0),
    "wj":Q(f__consumption_and_capital_investment__gt=0),
    "wk":Q(f__cost__gt=0),
    "wl":Q(f__cost_analysis__gt=0),
    "wm":Q(f__cost_benefit_analysis__gt=0),
    "wn":Q(f__cost_classification__gt=0),
    "wo":Q(f__cost_effectiveness__gt=0),
    "wp":Q(f__cost_of_living__gt=0),
    "wq":Q(f__curricula__gt=0),
    "wr":Q(f__curriculum__gt=0),
    "ws":Q(f__demand__gt=0),
    "wt":Q(f__decision_making__gt=0),
    "wu":Q(f__dialogic_pedagogy__gt=0),
    "wv":Q(f__dialogue__gt=0),
    "ww":Q(f__digital_economy__gt=0),
    "wx":Q(f__digital_goods_and_services__gt=0),
    "wy":Q(f__digital_trade__gt=0),
    "wz":Q(f__discriminatory_taxes__gt=0),
    "w0":Q(f__diversity__gt=0),
    "w1":Q(f__divided_societies__gt=0),
    "w2":Q(f__domestic_education_spending__gt=0),
    "w3":Q(f__donor__gt=0),
    "w4":Q(f__donor_sponsored__gt=0),
    "w5":Q(f__early_literacy__gt=0),
    "w6":Q(f__economic_factors__gt=0),
    "w7":Q(f__economics__gt=0),
    "w8":Q(f__education_financing__gt=0),
    "w9":Q(f__education_rbf__gt=0),
    "xa":Q(f__education_results_based_financing__gt=0),
    "xb":Q(f__educational_equality__gt=0),
    "xc":Q(f__educational_equity__gt=0),
    "xd":Q(f__educational_opportunities__gt=0),
    "xe":Q(f__efficiency__gt=0),
    "xf":Q(f__emancipation__gt=0),
    "xg":Q(f__empowerment__gt=0),
    "xh":Q(f__equity__gt=0),
    "xi":Q(f__exclusion__gt=0),
    "xj":Q(f__expenditures__gt=0),
    "xk":Q(f__expense__gt=0),
    "xl":Q(f__female__gt=0),
    "xm":Q(f__federal_aid__gt=0),
    "xn":Q(f__finance__gt=0),
    "xo":Q(f__financers__gt=0),
    "xp":Q(f__financial_feasibility__gt=0),
    "xq":Q(f__financial_policy__gt=0),
    "xr":Q(f__financial_stream__gt=0),
    "xs":Q(f__financial_support__gt=0),
    "xt":Q(f__financing__gt=0),
    "xu":Q(f__flexible__gt=0),
    "xv":Q(f__fund_raising__gt=0),
    "xw":Q(f__funder__gt=0),
    "xx":Q(f__funding__gt=0),
    "xy":Q(f__funding_formula__gt=0),
    "xz":Q(f__funding_proposals__gt=0),
    "x0":Q(f__fundraising__gt=0),
    "x1":Q(f__gender__gt=0),
    "x2":Q(f__gender_equality__gt=0),
    "x3":Q(f__girl__gt=0),
    "x4":Q(f__government__gt=0),
    "x5":Q(f__government_funding__gt=0),
    "x6":Q(f__government_role__gt=0),
    "x7":Q(f__high_tariffs__gt=0),
    "x8":Q(f__improvement__gt=0),
    "x9":Q(f__incentives__gt=0),
    "ya":Q(f__incidental_learning__gt=0),
    "yb":Q(f__inclusion__gt=0),
    "yc":Q(f__inclusive_education__gt=0),
    "yd":Q(f__inclusive_learning__gt=0),
    "ye":Q(f__information_sciences__gt=0),
    "yf":Q(f__instructional_design__gt=0),
    "yg":Q(f__instructionalism__gt=0),
    "yh":Q(f__interactionism__gt=0),
    "yi":Q(f__interactive_pedagogy__gt=0),
    "yj":Q(f__interactive_teaching__gt=0),
    "yk":Q(f__intercultural__gt=0),
    "yl":Q(f__integration__gt=0),
    "ym":Q(f__internet_economy__gt=0),
    "yn":Q(f__investments__gt=0),
    "yo":Q(f__leadership__gt=0),
    "yp":Q(f__learning_ecologies__gt=0),
    "yq":Q(f__life_wide_learning__gt=0),
    "yr":Q(f__lifelong_learning__gt=0),
    "ys":Q(f__limitations__gt=0),
    "yt":Q(f__literacy__gt=0),
    "yu":Q(f__literacy_assessment__gt=0),
    "yv":Q(f__management__gt=0),
    "yw":Q(f__millennium_development_goals__gt=0),
    "yx":Q(f__ministry__gt=0),
    "yy":Q(f__monitoring_and_evaluation__gt=0),
    "yz":Q(f__monitoring_evaluation_and_learning__gt=0),
    "y0":Q(f__motivation__gt=0),
    "y1":Q(f__mulitlingual_education__gt=0),
    "y2":Q(f__neo_colonialism__gt=0),
    "y3":Q(f__neo_liberalism__gt=0),
    "y4":Q(f__neocolonialism__gt=0),
    "y5":Q(f__neoliberalism__gt=0),
    "y6":Q(f__non_mother_tongue_language_acquisition__gt=0),
    "y7":Q(f__numeracy__gt=0),
    "y8":Q(f__numeracy_assessment__gt=0),
    "y9":Q(f__opportunity_cost__gt=0),
    "za":Q(f__outcomes__gt=0),
    "zb":Q(f__pay__gt=0),
    "zc":Q(f__payment__gt=0),
    "zd":Q(f__pedagogy__gt=0),
    "ze":Q(f__personalised_teaching__gt=0),
    "zf":Q(f__philanthropic_foundations__gt=0),
    "zg":Q(f__policy__gt=0),
    "zh":Q(f__private_financial_support__gt=0),
    "zi":Q(f__private_public_partnership__gt=0),
    "zj":Q(f__pro_poor__gt=0),
    "zk":Q(f__problem_based_learning__gt=0),
    "zl":Q(f__profit__gt=0),
    "zm":Q(f__profitability__gt=0),
    "zn":Q(f__public_expenditure_on_education__gt=0),
    "zo":Q(f__public_relations__gt=0),
    "zp":Q(f__reading__gt=0),
    "zq":Q(f__regulation__gt=0),
    "zr":Q(f__remuneration__gt=0),
    "zs":Q(f__resource_allocation__gt=0),
    "zt":Q(f__returns__gt=0),
    "zu":Q(f__rewards__gt=0),
    "zv":Q(f__rural__gt=0),
    "zw":Q(f__salary__gt=0),
    "zx":Q(f__scalabilty__gt=0),
    "zy":Q(f__scholarships__gt=0),
    "zz":Q(f__school_management__gt=0),
    "z0":Q(f__sustainable_development_goals__gt=0),
    "z1":Q(f__service_providers__gt=0),
    "z2":Q(f__socio_culturalism__gt=0),
    "z3":Q(f__socioeconomic_status__gt=0),
    "z4":Q(f__special_needs__gt=0),
    "z5":Q(f__standards__gt=0),
    "z6":Q(f__state_aid__gt=0),
    "z7":Q(f__supply__gt=0),
    "z8":Q(f__sustainability__gt=0),
    "z9":Q(f__sustainable_revenue_streams__gt=0),
    "0a":Q(f__systems__gt=0),
    "0b":Q(f__taxation_regimes__gt=0),
    "0c":Q(f__taxes__gt=0),
    "0d":Q(f__teacher_absenteeism__gt=0),
    "0e":Q(f__teacher_attendance__gt=0),
    "0f":Q(f__teacher_identity__gt=0),
    "0g":Q(f__teacher_motivation__gt=0),
    "0h":Q(f__teaching_approach__gt=0),
    "0i":Q(f__teaching_method__gt=0),
    "0j":Q(f__trade_and_investment_system__gt=0),
    "0k":Q(f__training_needs__gt=0),
    "0l":Q(f__training_pathway__gt=0),
    "0m":Q(f__women__gt=0),
    "0n":Q(f__urban__gt=0)
}

hdi_values = {
   "ab": 0.498,
   "ac": 0.785,
   "ad": 0.754,
   "ae": 0.858,
   "af": 0.581,
   "ag": 0.78,
   "ah": 0.825,
   "ai": 0.755,
   "ak": 0.939,
   "al": 0.908,
   "am": 0.757,
   "an": 0.807,
   "ao": 0.846,
   "ap": 0.608,
   "aq": 0.8,
   "ar": 0.808,
   "as": 0.916,
   "at": 0.708,
   "au": 0.515,
   "av": 0.612,
   "aw": 0.693,
   "ax": 0.768,
   "ay": 0.717,
   "az": 0.759,
   "a0": 0.853,
   "a1": 0.813,
   "a2": 0.423,
   "a3": 0.417,
   "a4": 0.582,
   "a5": 0.556,
   "a6": 0.926,
   "a7": 0.654,
   "a9": 0.367,
   "ba": 0.404,
   "bb": 0.843,
   "bc": 0.752,
   "bd": 0.747,
   "be": 0.503,
   "bf": 0.457,
   "bg": 0.606,
   "bi": 0.794,
   "bj": 0.492,
   "bk": 0.831,
   "bl": 0.777,
   "bm": 0.869,
   "bn": 0.888,
   "bo": 0.929,
   "bp": 0.476,
   "bq": 0.736,
   "br": 0.715,
   "bs": 0.625,
   "bt": 0.752,
   "bu": 0.696,
   "bv": 0.674,
   "bw": 0.44,
   "bx": 0.871,
   "by": 0.588,
   "bz": 0.463,
   "b0": 0.741,
   "b1": 0.92,
   "b2": 0.901,
   "b3": 0.702,
   "b4": 0.46,
   "b5": 0.78,
   "b6": 0.936,
   "b7": 0.592,
   "b8": 0.87,
   "b9": 0.772,
   "ca": 0.65,
   "cb": 0.455,
   "cc": 0.591,
   "cd": 0.459,
   "ce": 0.654,
   "cf": 0.498,
   "cg": 0.617,
   "ch": 0.838,
   "ci": 0.935,
   "cj": 0.64,
   "ck": 0.694,
   "cl": 0.798,
   "cm": 0.685,
   "cn": 0.938,
   "co": 0.903,
   "cp": 0.88,
   "cq": 0.732,
   "cr": 0.909,
   "cs": 0.735,
   "ct": 0.8,   
   "cu": 0.59,
   "cv": 0.612,
   "cy": 0.903,
   "c1": 0.803,
   "c2": 0.672,
   "c3": 0.601,
   "c4": 0.847,
   "c5": 0.757,
   "c6": 0.52,
   "c7": 0.435,
   "c8": 0.706,
   "c9": 0.916,
   "da": 0.858,
   "db": 0.904,
   "dc": 0.519,
   "dd": 0.477,
   "de": 0.802,
   "df": 0.717,
   "dg": 0.427,
   "dh": 0.878,
   "di": 0.708,
   "dj": 0.52,
   "dk": 0.79,
   "dl": 0.774,
   "dm": 0.627,
   "dn": 0.7,
   "dq": 0.741,
   "dr": 0.814,
   "ds": 0.667,
   "dt": 0.437,
   "du": 0.578,
   "dv": 0.647,
   "dx": 0.574,
   "dy": 0.931,
   "dz": 0.917,
   "d0": 0.658,
   "d1": 0.354,
   "d2": 0.532,
   "d4": 0.757,
   "d5": 0.953,
   "d6": 0.821,
   "d7": 0.562,
   "d8": 0.798,
   "d9": 0.686,
   "ea": 0.789,
   "eb": 0.544,
   "ec": 0.702,
   "ed": 0.75,
   "ee": 0.699,
   "ef": 0.865,
   "eg": 0.847,
   "ei": 0.856,
   "ej": 0.811,
   "ek": 0.816,
   "el": 0.524,
   "eo": 0.747,
   "ep": 0.723,
   "eq": 0.713,
   "es": 0.589,
   "et": 0.853,
   "eu": 0.505,
   "ev": 0.787,
   "ew": 0.797,
   "ex": 0.419,
   "ey": 0.932,
   "ez": 0.855,
   "e0": 0.896,
   "e1": 0.546,
   "e4": 0.699,
   "e5": 0.903,
   "e7": 0.388,
   "e8": 0.891,
   "e9": 0.77,
   "fa": 0.502,
   "fb": 0.72,
   "fc": 0.933,
   "fd": 0.944,
   "fe": 0.536,
   "ff": 0.65,
   "fg": 0.538,
   "fh": 0.755,
   "fj": 0.503,
   "fk": 0.726,
   "fl": 0.784,
   "fm": 0.735,
   "fn": 0.791,
   "fo": 0.706,
   "fq": 0.516,
   "fr": 0.751,
   "fs": 0.863,
   "ft": 0.922,
   "fu": 0.924,
   "fv": 0.804,
   "fw": 0.71,
   "fx": 0.603,
   "fz": 0.761,
   "f0": 0.694,
   "f1": 0.452,
   "f2": 0.588,
   "f3": 0.535
}


def explain_character_with_dict_existence(field_value, output_query):
    if field_value in search_filter:
        if output_query == None:
            output_query = search_filter[field_value]
        else:
            output_query |= search_filter[field_value]
    return output_query


def check_hdi(bottom_value, top_value, value_index, country):
    if country in value_index:
        hdi_value = value_index[country] 
        if (hdi_value > float(bottom_value)) and (hdi_value < float(top_value)):
            return True
        return False
    else:
        return True


def query_function(tak=None, author=None, yearmin=None, yearmax=None, form_gc_gr=None, form_gd=None, form_p1_p2=None, form_te_tt=None, form_f=None, form_o=None, form_r=None, below_rank_10=True, min_hdi=None, max_hdi=None):
    large_filter = Q()
    if tak:
        tak_query = SearchQuery(tak, search_type='websearch')
        large_filter &= Q(tsv=tak_query)
    if author:
        author_query = SearchQuery(author, search_type='websearch')
        large_filter &= Q(tsa=author_query)
    if yearmin:
        large_filter &= Q(year__gte=yearmin)
    if yearmax:
        large_filter &= Q(year__lte=yearmax)
    if form_gc_gr and form_gd:
        g_query = Q()
        for gc_gr_value in form_gc_gr:
            if min_hdi and max_hdi:
                if check_hdi(min_hdi, max_hdi, hdi_values, gc_gr_value) == True:
                    g_query = explain_character_with_dict_existence(gc_gr_value, g_query)
            else:
                form_gc_query = explain_character_with_dict_existence(gc_gr_value, g_query)
        for gd_value in form_gd:
            g_query = explain_character_with_dict_existence(gd_value, g_query) 
        large_filter &= Q(g_query)
    if form_gc_gr and not form_gd:
        g_query = Q()
        for gc_gr_value in form_gc_gr:
            if min_hdi and max_hdi:
                if check_hdi(min_hdi, max_hdi, hdi_values, gc_gr_value) == True:
                    g_query = explain_character_with_dict_existence(gc_gr_value, g_query)
            else:
                g_query = explain_character_with_dict_existence(gc_gr_value, g_query)
        large_filter &= Q(g_query)
    if form_gd and not form_gc_gr:
        g_query = Q()
        for gd_value in form_gd:
            g_query = explain_character_with_dict_existence(gd_value, g_query) 
        large_filter &= Q(g_query)
    if form_p1_p2:
        p_query = Q()
        for p_value in form_p1_p2:
            p_query = explain_character_with_dict_existence(p_value, p_query) 
        large_filter &= Q(p_query)
    if form_te_tt:
        t_query = Q()
        for t_value in form_te_tt:
            t_query = explain_character_with_dict_existence(t_value, t_query) 
        large_filter &= Q(t_query)
    if form_o:
        o_query = Q()
        for o_value in form_o:
            o_query = explain_character_with_dict_existence(o_value, o_query) 
        large_filter &= Q(o_query)
    if form_f:
        f_query = Q()
        for f_value in form_f:
            f_query = explain_character_with_dict_existence(f_value, f_query) 
        large_filter &= Q(f_query)
    if form_r:
        r_query = Q()
        for r_value in form_r:
            r_query = explain_character_with_dict_existence(r_value, r_query) 
        large_filter &= Q(r_query)

    if large_filter == Q():
        return large_filter
    if below_rank_10 == True:
        large_filter &= Q(relevance__relevance__gt=10)
    return large_filter

def formulate_tak_query(query_string):
	query_parts = Q()

	for _q in query_string.split(" AND "):

		not_flag = re.findall("\s*NOT\s*", _q)
		_q = re.sub("\s*NOT\s*", "", _q)

		# remove single quote
		_q = re.sub("^\s*\'", "", _q)
		_q = re.sub("'\s*$", "", _q)

		# remove single quote
		_q = re.sub("^\s*\(\s*\'", "", _q)
		_q = re.sub("'\s*\)\s*$", "", _q)

		if not_flag:
			query_parts &= ~Q(tak__iregex=_q)
		else:
			query_parts &= Q(tak__iregex=_q)

	return query_parts


def faster_count():
    with connection.cursor() as cursor:
        cursor.execute("SELECT reltuples::bigint AS __count FROM pg_class WHERE relname = 'publications';")
        est_count = int(cursor.fetchone()[0])

    return est_count

