"""
Django settings for spud project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import logging

import environ
env = environ.Env(
    ALLOWED_HOSTS=(list, ['127.0.0.1', 'localhost']),
)
environ.Env.read_env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_true'],
        },
    },
    'loggers': {
        'mylogger': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
    },
}

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# Application definition

INSTALLED_APPS = [
    'publications.apps.PublicationsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
if os.getenv('GAE_APPLICATION', None):
    # this is for server settings on google application engine
    SECURE_SSL_REDIRECT = True

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': env("PRODUCTION_HOST"),
            'NAME': env("PRODUCTION_DATABASE_NAME"),
            'USER': env("PRODUCTION_USER"),
            'PASSWORD': env("PRODUCTION_PASSWORD"),
            'PORT': env("PRODUCTION_PORT"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': env("STAGING_HOST"),
            'NAME': env("STAGING_DATABASE_NAME"),
            'USER': env("STAGING_USER"),
            'PASSWORD': env("STAGING_PASSWORD"),
            'PORT': env("STAGING_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

WITH_FILTERS = {
    "GC.H": {
        "regex": [],
        "iregex": ["\y(Chad|Ghana|India|Kenya|Mali|Nepal|Niger|Peru|Sudan)\y", "(Bangladesh|Burkina Faso|Burundi|Central African Republic|Comoros|Democratic Republic of the Congo|Eritrea|Ethiopia|Gambia|Guinea.Bissau|Jordan|Lebanon|Liberia|Malawi|Mozambique|Nigeria|Pakistan|Philippines|Rwanda|Sierra Leone|South Sudan|United Republic of Tanzania|Uganda|Zambia|Zimbabwe)"],
    },

    "GC.H or GC.M": {
        "regex": ["\y(DRC|RSA)\y"],
        "iregex": ["\y(Niger|Nigeran)\y", "(Chad|Ghana|India|Kenya|Mali|Nepal|Niger|Peru|Sudan|Benin|China|Congo|Cuba|Egypt|Fiji|Gabon|Haiti|Iraq|Iraq|Laos|Libya|Burma|Nauru|Nauru|Syria|Tibet|Togo|Yemen|Bangladesh|Burkina Faso|Burundi|Central African Republic|Comoros|Democratic Republic of the Congo|Eritrea|Ethiopia|Gambia|Guinea.Bissau|Jordan|Lebanon|Liberia|Malawi|Mozambique|Nigeria|Pakistan|Philippines|Rwanda|Sierra Leone|South Sudan|United Republic of Tanzania|Uganda|Zambia|Zimbabwe|Abkhazia|Afghanistan|Algeria|Angola|Armenia|Artsakh|Nagorno.Karabakh|Azerbaijan|Belize|Bhutan|Bolivia|Plurinational State of Bolivia|Bosnia and Herzegovina|Botswana|Brazil|Cambodia|Cameroon|Cabo Verde|Cape Verde|Central African Republic|Colombia|Republic of the Congo|Costa Rica|Côte d.Ivoire|Ivory Coast|Congo|Djibouti|Dominican Republic|East Timor|Timor L.este|Timor.L.este|Ecuador|El Salvador|El Salvador|Equatorial Guinea|eSwatini|Eswatini|Kingdom of Eswatini|Swaziland|Swaziland|Gambia|Guatemala|Guinea|Guinea|Guyana|Honduras|Indonesia|Jamaica|Kiribati|Kurdistan|Kyrgyzstan|Kyrgyzstan|Kyrgyzstan|Laos People.s Democratic Republic|Lesotho|Liberia|Madagascar|Maldives|Maldives|Mauritania|Mauritius|Mauritius|Mexico|Federated States of Micronesia|Micronesia|Moldova|Republic of Moldova|Mongolia|Morocco|Myanmar|Namibia|Nicaragua|North Korea|North Macedonia|Macedonia|Republic of North Macedonia|The former Yugoslav Republic of Macedonia|Palestine|Palestine, State of|State of Palestine|Panama|Papua New Guinea|Paraguay|Pridnestrovian Moldovan Republic|Transnistria|Puntland|Romania|Russia|Russian Federation|Sahrawi Arab Democratic Republic|Sahrawi Republic|Western Sahara|Saint Lucia|Sao Tome and Principe|São Tomé and Príncipe|Senegal|Serbia|Solomon Islands|Somalia|Somaliland|Republic of South Africa|South Africa|South Ossetia|the State of Alania|Sri Lanka|Suriname|Suriname|Syrian Arab Republic|Tajikistan|Tanzania|Thailand|Tunisia|Turkey|Turkmenistan|Tuvalu|Ukraine|Uzbekistan|Vanuatu|Bolivarian Republic of Venezuela|Venezuela|Viet Nam|Vietnam)"],
    },

    "GC.HM or GR or GD": {
        "regex": ["\y(DRC|RSA|AFR|EAC|EAP|ECA|LAC|MENA|SIDS|SADC|SAR|SSA|LMIC)\y"],
        "iregex": ["\y(Chad|Ghana|India|Kenya|Mali|Nepal|Niger|Peru|Sudan|Benin|China|Congo|Cuba|Egypt|Fiji|Gabon|Haiti|Iraq|Iraq|Laos|Libya|Burma|Nauru|Nauru|Syria|Tibet|Togo|Yemen|LMICs)\y", "(Bangladesh|Burkina Faso|Burundi|Central African Republic|Comoros|Democratic Republic of the Congo|Eritrea|Ethiopia|Gambia|Guinea.Bissau|Jordan|Lebanon|Liberia|Malawi|Mozambique|Nigeria|Pakistan|Philippines|Rwanda|Sierra Leone|South Sudan|United Republic of Tanzania|Uganda|Zambia|Zimbabwe|Abkhazia|Afghanistan|Algeria|Angola|Armenia|Artsakh|Nagorno.Karabakh|Azerbaijan|Belize|Bhutan|Bolivia|Plurinational State of Bolivia|Bosnia and Herzegovina|Botswana|Brazil|Cambodia|Cameroon|Cabo Verde|Cape Verde|Central African Republic|Colombia|Congo, Rep.|Congo, Rep.|Rep. of the Congo|Republic of the Congo|Republic of the Congo|Costa Rica|Côte d.Ivoire|Ivory Coast|Congo, Dem. Rep.|Congo, Democratic Republic of the|Dem. Rep. of the Congo|Democratic Republic of the Congo|Djibouti|Dominican Republic|East Timor|Timor L.este|Timor.L.este|Ecuador|El Salvador|El Salvador|Equatorial Guinea|eSwatini|Eswatini|Kingdom of Eswatini|Swaziland|Swaziland|Islamic republic of the Gambia|Republic of the Gambia|Georgia|Guatemala|Guinea|Guinea|Guyana|Honduras|Indonesia|Jamaica|Kiribati|Kurdistan|Kyrgyzstan|Kyrgyzstan|Kyrgyzstan|Laos People.s Democratic Republic|Lesotho|Liberia|Madagascar|Maldives|Maldives|Mauritania|Mauritius|Mauritius|Mexico|Federated States of Micronesia|Micronesia|Moldova|Republic of Moldova|Mongolia|Morocco|Myanmar|Namibia|Nicaragua|North Korea|North Macedonia|Rep. of Macedonia|Republic of North Macedonia|The former Yugoslav Republic of Macedonia|Palestine|Palestine, State of|State of Palestine|Panama|Papua New Guinea|Paraguay|Pridnestrovian Moldovan Republic|Transnistria|Puntland|Romania|Russia|Russian Federation|Sahrawi Arab Democratic Republic|Sahrawi Republic|Western Sahara|Saint Lucia|Sao Tome and Principe|São Tomé and Príncipe|Senegal|Serbia|Solomon Islands|Somalia|Somaliland|Republic of South Africa|South Africa|South Ossetia|the State of Alania|Sri Lanka|Suriname|Suriname|Syrian Arab Republic|Tajikistan|Tanzania|Thailand|Tunisia|Turkey|Turkmenistan|Tuvalu|Ukraine|Uzbekistan|Vanuatu|Bolivarian Republic of Venezuela|Venezuela|Viet Nam|Vietnam|Africa|Arab world|Asia.Pacific|Caribbean|Central Africa|Central America|Central Asia|East Africa|East Africa Community|East Asia|East Asia and Pacific|Eastern Africa|Eastern Asia|Europe and Central Asia|Horn of Africa|Latin America|Latin America and Caribbean|Micronesia|Middle Africa|Middle East|Middle East and North Africa|North Africa|Northern Africa|Pacific|Polynesia|Small Island Development States|Southern African Development Community|South America|South Asia|South Asia Region|Southeast Asia|Southeastern Asia|Southern Africa|Southern Asia|Sub.Saharan Africa|West Africa|Western Africa|Western Asia|conflict affected areas|conflict.affected areas|conflict affected regions|conflict.affected regions|conflict zones|developing context|developing countries|developing country|developing economies|developing economy|developing market countries|developing market country|developing markets|developing nation|developing region|developing state|developing world|emergent nation|emergent nations|emerging economies|emerging market countries|emerging market country|emerging nation|emerging world|fragile and conflict affected areas|fragile and conflict affected regions|fragile areas|fragile contexts|fragile regions|Global South|growing economies|less developed countries|less developed country|low and middle income countries|low income countries|low income country|low income environment|low resource countries|low resource country|low resource environment|low.income countries|low.income country|low.income environment|low.resource countries|low.resource country|low.resource environment|middle.income country|middle.income country|middle.income country|middle.income environment|middle income environment|third world|third.world|under developed countries|under developed country|under.developed countries|under.developed country|underdeveloped countries|underdeveloped country|under.developed nation|under developed nation|underdeveloped nation)"],
    },

    "PP": {
        "regex": ["\y(ECE|TPD|CPD|NFE|SEN|SEND|STEAM|STEM|TVET)\y", "(MoE|EiE)"],
        "iregex": ["(k-12|alien|math|slum|youth|district education officer|early childhood education|elementary school|headteacher|high school|junior middle school|junior school|k to 12|kindergarten|lower secondary|middle school|middle.school|ministry of education|nursery|post primary|post.primary|pre primary|pre.primary|pre.school|pre.service teachers|primary education|primary school|principal|school|school governing body|school head|school leadership team|school management team|school offical|school principal|school teacher|secondary education|secondary school|senior leadership team|teacher candidates|teacher certificate|teacher community of practice|teacher communities of practice|teacher COP|teacher education|teacher professional development|teacher training|teacher training centre|teacher training college|teacher training institute|teachers|teaching certificate|classroom assistants|classroom instruction|classroom teaching|early childhood development|educators|elementary education|faith school|private school|refugee educator|school administrator|school authority|school director|school supervisor|state school|teaching assistant|teaching assistant|teaching assistants|accessible learning|alienation|asylum|asylum seeker|at.risk population|bachelor.s degree|bachelors degree|career.entry support|career entry support|career path training|church|community education|competency.based training|continuing education|continuing training|continuous professional development|degree|diploma|disabilities|disability|district.level|displaced person|displaced populations|education|education in emergencies|favela|fragility in education|gang members|geographically dispersed|in.service training|informal education|informal learning|informal training|language learning|learning community|master.s degree|masters|mathematics|migrant|minority ethnic group|mosque|moving populations|natural science|Non.formal education|non.formal learning|Postsecondary Education|pre.service training|professional continuing education|professional education|professional learning community|professional learning communities|professional qualification|professional re.education|professional studies|professional training|qualification|refugee education|refugee learning|science|science and technology|Science Technology Engineering and Applied Mathematics|Science Technology Engineering and Mathematics|special educational needs|SEN learner|SEN student|special educational needs and disabilities|special needs students|street children|students|students with disabilities|technical training|Technical and vocational education and training|Vocational training|young people)"],
    },

    "TE": {
        "regex": ["(CAI|CAL|FDL|ODEL|ODL|RLO|TETS|CMS|EMIS|FDR|LMS|MOOC|OER|TEL|VLE)", "(MOOCs)"],
        "iregex": ["(adaptive learning|asynchronous learning|computer assisted instruction|Computer assisted learning|computer based assessment|computer based instruction|computer.based instruction|computer managed instruction|computer mediated learning|computer.mediated learning|Computer supported collaborative learning|computer supported education|computer.supported education|Computer.assisted instructional programme|computerised learning|computerized learning|connected learning|digital.learning|distance learning|distance learning program|educational innovation|electronic classroom|e.tutor|Etutor|examination systems|flipped learning|free digital learning|gamification|instructional innovation|instructional technology|integrated learning systems|Intelligent agent|Intelligent tutoring system|media literacy|micro learning|micro.learning|microlearning|multimedia instruction|online course|online lab|online laboratory|online learning|online textbook|Online tutor|open learning|personalised teaching|Plasma.based instruction|Reusable learning object|School website|Synchronous online learning|Teacher development software|technological pedagogical content|Technology engagement teaching strategy|technology integration|tele education|tele.education|teleeducation|textbook analytics|virtual learning|Virtual school|web based instruction|web.based instruction|webinar|blended learning|computer.assisted instruction|Course Management System|Differentiated learning|digital learning|distance education|distributed learning|e.learning|elearning|electronic learning|EdTech|Education Technology|Educational Technology|Education Management Information System|Educational technologies|e textbook|e.textbook|electronic textbook|etextbook|electronic whiteboard|Emerging education technologies|Emerging education technology|flipped classroom|free digital resources|H.learning|hybrid learning|ICT in classrooms|ICT in the classroom|Individualised learning|Interactive learning environment|interactive whiteboard|ubiquitous learning|learning management system|Learning platform|massive open online course|m education|m.education|meducation|mobile education|m learning|m.learning|mlearning|Mobile learning|open educational resources|open and distance elearning|open and distance e.learning|open and distance learning|open education|personalised learning|Self.directed learning|self.paced learning|smart board|smartboard|technology assisted learning|technology at school|Technology enhanced learning|Technology.enhanced learning|technology in education|technology in school|technology use in education|technology.assisted learning|virtual classroom|virtual learning environment)"],
    },

    "TT": {
        "regex": ["(BADA|CMC|ICT|IOS|IoT|IT|QQ|RACHEL|TV|VR)"],
        "iregex": ["\y(app|Apple|blog|cloud|COWs|data|i.pad|intel|ipad|Maemo|MeeGo|QZone|radio|Viber|Web|WiFi|Ebook)\y", "(3D printer|3D printing|access to computers|accessible technologies|alternative communication|android|application|audio recording|augmentative communication|barriers to technology|big data|Blackberry|camera|cellphone|Chatbot|clicker technology|clickers|computational thinking literacy|computer illiteracy|computer literacy|Computer.mediated communication|computerised|computers on wheels|Connectivity|CT literacy|digital communication|digital content|digital exclusion|Digital immigrants|digital inclusion|Digital native|Digital scrapbook|digital storytelling|digital technology|digital transformation|digitalised|digitised|Discord|Disruptive technology|Douban|Douyin|DVD player|earphones|Facebook|game console|Garnet|Geographical information systems|hardware|headphones|holograms|ICT goods and services|inclusive technologies|influence of technology|Information communications technology literacy|information literacy|Instagram|instructional systems|instructional technology|integration of technology|interactive|Internet|internet access|internet domain|iphone|information technology|keyboard|kindle|laptop|LinkedIn|metadata|microsoft|new media|new technologies|offline|online|online discussion|online lab|open source|open source software|Open wedOS|operating system|Palm OS|Pinterest|platform|podcast|Poll Everywhere|printer|RACHEL server|Reddit|SD card|simulation|Sina Weibo|single board computer|Snapchat|social network|social networking sites|software|supportive technology|Symbian|technological literacy|technology leapfrogging|technology.enhanced|telephone|television|TikTok|Twitter|Verdict|video recorder|videoconferencing|virtual peer|Virtual reality|WeChat|Wikipedia|Windows|Youtube|moodle|digital skills|assistive technology|bandwidth|computer|digital divide|digital literacy|Digital resources|e.book|e.reader|ereader|gadget|information and communication technology|internet of things|mobile phone|Raspberry Pi|social media|tablet|WhatsApp)"],
    },

    "TT and PP": "TT AND PP",
    "TE or (TT and PP)": "TE OR (TT AND PP)",

    "Bangladesh": "Bangladesh",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Central African Republic": "Central African Republic",
    "Chad": "Chad",
    "Comoros": "Comoros",
    "Congo": "Congo",
    "Eritrea": "Eritrea",
    "Ethiopia": "Ethiopia",
    "Gambia": "Gambia",
    "Ghana": "Ghana",
    "Guinea.Bissau": "Guinea.Bissau",
    "India": "India",
    "Jordan": "Jordan",
    "Kenya": "Kenya",
    "Lebanon": "Lebanon",
    "Liberia": "Liberia",
    "Malawi": "Malawi",
    "Mali": "Mali",
    "Mozambique": "Mozambique",
    "Nepal": "Nepal",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "Pakistan": "Pakistan",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Rwanda": "Rwanda",
    "Sierra Leone": "Sierra Leone",
    "South Sudan": "South Sudan",
    "Sudan": "Sudan",
    "Tanzania": "Tanzania",
    "Uganda": "Uganda",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe",
}

COUNTRIES = ["AFR", "Abkhazia", "Afghanistan", "Algeria", "Angola", "Aotearoa", "Armenia", "Artsakh", "Azerbaijan", "Bangladesh", "Belize", "Benin", "Bhutan", "Bolivarian Republic of Venezuela", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Burkina Faso", "Burma", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Cape Verde", "Central African Republic", "Chad", "China", "Colombia", "Comoros", "Congo", "Congo, Dem. Rep.", "Congo, Democratic Republic of the", "Congo, Rep.", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Côte d'Ivoire", "DRC", "Dem. Rep. of the Congo", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "EAC", "EAP", "ECA", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Federated States of Micronesia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Islamic republic of the Gambia", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kingdom of Eswatini", "Kiribati", "Korea (Republic of)", "Kosovo", "Kurdistan", "Kuwait", "Kyrgyzstan", "LAC", "LMIC", "LMICs", "Laos", "Laos People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "MENA", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Nagorno-Karabakh", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Cyprus", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Palestine, State of", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Plurinational State of Bolivia", "Poland", "Portugal", "Pridnestrovian Moldovan Republic", "Puntland", "Qatar", "RSA", "Rep. of Macedonia", "Rep. of the Congo", "Republic of Moldova", "Republic of North Macedonia", "Republic of South Africa", "Republic of the Congo", "Republic of the Gambia", "Romania", "Russia", "Russian Federation", "Rwanda", "SADC", "SAR", "SIDS", "SSA", "Sahrawi Arab Democratic Republic", "Sahrawi Republic", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "Somaliland", "South Africa", "South Korea", "South Ossetia", "South Sudan", "Spain", "Sri Lanka", "State of Palestine", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Syrian Arab Republic", "São Tomé and Príncipe", "Tajikistan", "Tanzania", "Thailand", "The former Yugoslav Republic of Macedonia", "Tibet", "Timor L'este", "Timor-L'este", "Togo", "Tonga", "Transnistria", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United Republic of Tanzania", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Viet Nam", "Vietnam", "Western Sahara", "Yemen", "Zambia", "Zimbabwe", "eSwatini", "the State of Alania"]
REGIONS =  ["AFR", "Africa", "Arab world", "Asia-Pacific", "Caribbean", "Central Africa", "Central America", "Central Asia", "EAC", "EAP", "ECA", "East Africa", "East Africa Community", "East Asia ", "East Asia and Pacific", "Eastern Africa", "Eastern Asia", "Europe and Central Asia", "Horn of Africa", "LAC", "Latin America ", "Latin America and Caribbean", "MENA", "Micronesia", "Middle Africa", "Middle East", "Middle East and North Africa", "North Africa", "Northern Africa", "Pacific", "Polynesia", "SADC", "SAR", "SIDS", "SSA", "Small Island Development States", "South America", "South Asia", "South Asia Region", "Southeast Asia", "Southeastern Asia", "Southern Africa", "Southern African Development Community ", "Southern Asia", "Sub-Saharan Africa", "West Africa", "Western Africa", "Western Asia"]
DEVELOPMENT_TERMS = ["Global South", "LMIC", "LMICs", "conflict affected areas", "conflict affected regions", "conflict zones", "conflict-affected areas", "conflict-affected regions", "developing context", "developing countries", "developing country", "developing economies", "developing economy", "developing market countries", "developing market country", "developing markets", "developing nation", "developing region", "developing state", "developing world", "emergent nation", "emergent nations", "emerging economies", "emerging market countries", "emerging market country", "emerging nation", "emerging world", "fragile and conflict affected areas", "fragile and conflict affected regions", "fragile areas", "fragile contexts", "fragile regions", "growing economies", "less developed countries", "less developed country", "low and middle income countries", "low income countries", "low income country", "low income environment", "low resource countries", "low resource country", "low resource environment", "low-income countries", "low-income country", "low-income environment", "low-resource countries", "low-resource country", "low-resource environment", "middle income environment", "middle-income country", "middle-income environment", "third world", "third-world", "under developed countries", "under developed country", "under developed nation", "under-developed countries", "under-developed country", "under-developed nation", "underdeveloped countries", "underdeveloped country", "underdeveloped nation"]
TECH_TERMS = ["3D printer", "3D printing", "Apple", "BADA", "Blackberry", "CMC", "COWs", "CT literacy", "Chatbot", "Computer-mediated communication", "Connectivity", "DVD player", "Digital immigrants", "Digital native", "Digital resources", "Digital scrapbook", "Discord", "Disruptive technology", "Douban", "Douyin", "Ebook", "Facebook", "Garnet ", "Geographical information systems", "I.T.", "ICT", "ICT goods and services", "IOS", "IT", "Information communications technology literacy", "Instagram", "Internet", "LinkedIn", "Maemo", "MeeGo", "Open wedOS", "Palm OS", "Pinterest", "Poll Everywhere", "QQ", "QZone", "RACHEL", "RACHEL server", "Raspberry Pi", "Reddit", "SD card", "Sina Weibo", "Snapchat", "Symbian", "TV", "TikTok", "Twitter", "VR", "Verdict", "Viber", "Virtual reality", "WeChat", "Web", "WhatsApp", "WiFi", "Wikipedia", "Windows", "Youtube", "access to computers", "accessible technologies", "alternative communication", "android", "app", "application", "assistive technology", "audio recording", "augmentative communication", "bandwidth", "barriers to technology", "big data", "blog", "camera", "cellphone", "clicker technology", "clickers", "cloud", "computational thinking literacy", "computer", "computer illiteracy", "computer literacy", "computerised", "computers on wheels", "data", "digital communication", "digital content", "digital divide", "digital exclusion", "digital inclusion", "digital literacy", "digital skills", "digital storytelling", "digital technology", "digital transformation", "digitalised", "digitised", "e-book", "e-reader", "earphones", "ereader", "gadget", "game console", "hardware", "headphones", "holograms", "i-pad", "inclusive technologies", "influence of technology", "information and communication technology", "information literacy", "information technology", "instructional systems", "instructional technology", "integration of technology", "intel", "interactive", "internet access", "internet domain", "internet of things", "ipad", "iphone", "keyboard", "kindle", "laptop", "metadata", "microsoft", "mobile phone", "new media", "new technologies", "offline", "online", "online discussion", "online lab", "open source", "open source software", "operating system", "platform", "podcast", "printer", "radio", "simulation", "single board computer", "social media", "social network", "social networking sites", "software", "supportive technology", "tablet", "technological literacy", "technology leapfrogging", "technology-enhanced", "telephone", "television", "video recorder", "videoconferencing", "virtual peer"]
EDUCATIONAL_TERMS = ["CAI", "CAL", "CMS", "Computer assisted learning", "Computer supported collaborative learning", "Computer-assisted instructional programme", "Course Management System", "Differentiated learning", "EMIS", "EdTech", "Education Management Information System", "Education Technology", "Educational Technology", "Educational technologies", "Emerging education technologies", "Emerging education technology", "Etutor", "FDL", "FDR", "H-learning", "ICT in classrooms", "ICT in the classroom", "Individualised learning", "Intelligent agent", "Intelligent tutoring system", "Interactive learning environment", "LMS", "Learning platform", "MOOC", "MOOCs", "Mobile learning", "ODEL", "ODL", "OER", "Online tutor", "Plasma-based instruction", "RLO", "Reusable learning object", "School website", "Self-directed learning", "Synchronous online learning", "TEL", "TETS", "Teacher development software", "Technology engagement teaching strategy", "Technology enhanced learning", "Technology-enhanced learning", "VLE", "Virtual school", "adaptive learning", "asynchronous learning", "blended learning", "computer assisted instruction", "computer based assessment", "computer based instruction", "computer managed instruction", "computer mediated learning", "computer supported education", "computer-assisted instruction", "computer-based instruction", "computer-mediated learning", "computer-supported education", "computerised learning", "computerized learning", "connected learning", "digital learning", "digital-learning", "distance education", "distance learning", "distance learning program", "distributed learning", "e textbook", "e-learning", "e-textbook", "e-tutor", "educational innovation", "elearning", "electronic classroom", "electronic learning", "electronic textbook", "electronic whiteboard", "etextbook", "examination systems", "flipped classroom", "flipped learning", "free digital learning", "free digital resources", "gamification", "hybrid learning", "instructional innovation", "instructional technology", "integrated learning systems", "interactive whiteboard", "learning management system", "m education", "m learning", "m-education", "m-learning", "massive open online course", "media literacy", "meducation", "micro learning", "micro-learning", "microlearning", "mlearning", "mobile education", "moodle", "multimedia instruction", "online course", "online lab", "online laboratory", "online learning", "online textbook", "open and distance e-learning", "open and distance elearning", "open and distance learning", "open education", "open educational resources", "open learning", "personalised learning", "personalised teaching", "self-paced learning", "smart board", "smartboard", "technological pedagogical content", "technology assisted learning", "technology at school", "technology in education", "technology in school", "technology integration", "technology use in education", "technology-assisted learning", "tele education", "tele-education", "teleeducation", "textbook analytics", "ubiquitous learning", "virtual classroom", "virtual learning", "virtual learning environment", "web based instruction", "web-based instruction", "webinar"]
POPULATION1 = ["ECE", "MoE", "TPD", "classroom assistants", "classroom instruction", "classroom teaching ", "district education officer ", "early childhood development", "early childhood education", "educators", "elementary education", "elementary school", "faith school", "headteacher", "high school", "junior middle school", "junior school", "k to 12", "k-12", "kindergarten ", "lower secondary ", "middle school", "middle-school", "ministry of education", "nursery", "post primary", "post-primary", "pre primary", "pre-primary", "pre-school", "pre-service teachers", "primary education", "primary school", "principal", "private school", "refugee educator", "school", "school administrator", "school authority", "school director ", "school governing body", "school head", "school leadership team", "school management team", "school offical ", "school principal", "school supervisor ", "school teacher", "secondary education", "secondary school", "senior leadership team", "state school", "teacher COP", "teacher candidates", "teacher certificate", "teacher communities of practice", "teacher community of practice", "teacher education", "teacher professional development", "teacher training", "teacher training centre", "teacher training college", "teacher training institute", "teachers", "teaching assistant", "teaching assistants", "teaching certificate"]
POPULATION2 = ["accessible learning", "alien", "alienation", "asylum", "asylum seeker ", "at-risk population", "bachelor's degree", "bachelors degree", "career-entry support", "career entry support", "career path training", "church", "community education", "competency-based training", "continuing education", "continuing training", "continuous professional development", "CPD", "degree", "diploma", "disabilities", "disability", "district-level", "displaced person", "displaced populations", "education", "education in emergencies", "EiE", "favela ", "fragility in education", "gang members", "geographically dispersed", "in-service training", "informal education", "informal learning", "informal training", "language learning ", "learning community", "master's degree", "masters", "math", "mathematics", "migrant", "minority ethnic group", "mosque", "moving populations", "natural science", "Non-formal education", "NFE", "non-formal learning", "Postsecondary Education", "pre-service training", "professional continuing education", "professional education", "professional learning community", "professional learning communities", "professional qualification", "professional re-education", "professional studies", "professional training", "qualification", "refugee education", "refugee learning", "science", "science and technology", "Science Technology Engineering and Applied Mathematics", "Science Technology Engineering and Mathematics", "slum", "special educational needs", "SEN", "SEN learner", "SEN student", "special educational needs and disabilities", "SEND", "special needs students", "STEAM", "STEM", "street children", "students", "students with disabilities", "technical training", "TVET", "Technical and vocational education and training", "Vocational training", "young people", "youth"]
ORGANISATIONS = ["ALISON", "BRCK", "Bridge", "Coursera", "Dr Maths", "EMO-Haiti", "ENLACES", "EkStep", "Eneza", "Enuma", "Foundation for Learning Equality", "Futurelearn", "Geekie", "Hip2BSquared", "KHANYA project", "Khan Academy", "Lego Project", "Mindspark", "Mobilearn", "Mxit", "Nafham", "OLE", "One Laptop Per Child ", "Pratham Books’ Storyweaver", "RETEL Haiti", "Rumie", "Scratch", "Siyavula", "TED", "The global digital library", "Ubongo", "Udacity", "University of the People", "WorldReader", "XuetangX", "Yoza", "cK-12", "edX", "egyptian teachers first professional development program", "inABLE", "khan academy", "kolibri", "one billion", "the connected learning initiative", "the egyptian knowledge bank", "the queen rania teacher academy"]
FOCUS = ["21st century learning", "Accountability", "Aid", "Bank", "Banking", "Budgeting", "Charity", "Constraints", "Cost", "Cost analysis", "Cost benefit analysis", "Cost classification", "Cost effectiveness", "Cost of living ", "Demand", "Domestic education spending", "Donor", "Economic Factors", "Economics", "Education RBF", "Education results-based financing", "Efficiency", "Expenditures", "Expense", "Federal Aid", "Female", "Finance", "Financers", "Financial feasibility", "Financial policy", "Financial support", "Financing", "Fund raising", "Funder", "Funding ", "Funding formula", "Funding proposals ", "Fundraising", "Government funding", "Government role", "Improvement", "Investments", "Limitations", "M&E", "MDG", "MEL", "Neo-colonialism", "Neo-liberalism", "Neocolonialism", "Neoliberalism", "Opportunity cost", "PBL", "PPP", "Philanthropic Foundations", "Private Public Partnership", "Private financial support", "Profit", "Profitability", "Public expenditure on education", "Public relations", "Resource Allocation", "Returns", "Rewards", "SDG", "Scalability", "Scholarships", "School management", "Socioeconomic Status", "State aid", "Supply", "Sustainability", "Taxes", "Trade and investment system", "academic achievement", "access", "access to education", "accessibility", "achievement", "achievement gap", "assessment", "attainment", "attendance ", "attitude", "attribution", "behavior", "behaviour", "change management", "constructivism", "constructivist", "consumption and capital investment", "curricula ", "curriculum", "decision-making", "dialogic learning", "dialogic pedagogy", "dialogic teaching ", "dialogue", "digital economy", "digital goods and services", "digital trade", "discriminatory taxes", "diversity", "divided societies", "donor-sponsored", "early literacy", "education financing", "educational equality", "educational equity", "educational opportunities", "emancipation", "empowerment", "equity", "exclusion", "financial stream", "flexible", "gender", "gender equality", "girl", "government", "high tariffs", "incentives", "incidental learning", "inclusion", "inclusive education", "inclusive learning", "information literacy", "information sciences", "instructional design", "instructional innovation", "instructionalism", "integration", "interactionism", "interactive", "interactive pedagogy", "interactive teaching", "intercultural ", "internet economy", "leadership", "learning", "learning ecologies", "life-wide learning", "lifelong learning", "literacy", "literacy assessment", "management", "media literacy", "millennium development goals", "ministry", "monitoring and evaluation", "monitoring evaluation and learning", "motivation", "non-mother-tongue language acquisition ", "numeracy", "numeracy assessment ", "outcomes", "pay", "payment", "pedagogy", "personalised learning", "personalised teaching", "policy", "pro-poor", "problem-based learning", "reading", "regulation", "remuneration", "rural ", "salary", "service providers", "socio-culturalism", "special needs", "standards", "sustainable development goals", "sustainable revenue streams", "systems", "taxation regimes", "teacher absenteeism ", "teacher attendance", "teacher identity", "teacher motivation", "teaching approach", "teaching method", "training needs", "training pathway", "urban", "women"]
RESEARCH = ["DBIR", "DBR", "EBR", "Multimethod", "Multiple research approach", "QED", "RCT", "action research", "adaptive", "agile", "anarchy", "case study", "citizen science", "combined research", "complement", "complementarity", "construct research", "correlation", "critical realism", "critical theory", "deductive", "design-based implementation research", "design-based research", "difference in differences", "engineering-based research", "evaluation", "experimental design", "field experiment ", "focus groups", "formative research", "grounded theory", "group discussions", "hermeneutics", "historical", "hybrid methods", "impact", "inductive", "integrated research", "interview", "iterative", "lean", "learning analytics", "literature analysis", "literature review", "long interview", "meta-analysis", "mixed analysis", "mixed method", "mixed methods", "mixed research", "mixed-method", "mixed-methods", "modelling", "multi-method", "multimethodology", "observation", "participatory video", "positivist", "program evaluation", "programme evaluation", "project design", "qualitative", "quantitative", "quasi-experimental design", "questionnaire", "randomised control trial", "randomised control trials", "randomized control trial", "randomized controlled trial", "randomized controlled trials", "randomly sampled", "regression", "regression discontinuity design", "representative sample", "research approach", "research design", "research method", "research methodology", "research methods", "rich text analysis", "semi-structured interview", "structured interview", "study design", "survey", "synthesis", "systematic review", "tracer study", "trial", "triangulate", "triangulation", "unstructured interview", "usability", "video"]

KEYWORDS = {
    "Countries": COUNTRIES,
    # "Regions": REGIONS,
    # "DevelopmentTerms": DEVELOPMENT_TERMS,
    # "TechTerms": TECH_TERMS,
    # "EducationalTerms": EDUCATIONAL_TERMS,
    # "Population1": POPULATION1,
    # "Population2": POPULATION2,
    # "Organizations": ORGANISATIONS,
    # "Focus": FOCUS,
    # "Research": RESEARCH,
}

AUTH_KEY = env("AUTH_KEY")

ABSTRACT_WORDS_LIMIT = 70
